.travis.yml, CONTRIBUTING.rst, docs/conf.py
The API documentation is broken on readthedocs for the 0.1.0 release as its configuration needed the package to be installed and imported. As installing the package requires large dependencies like torch, this is not desired.
This PR avoids the need to install the package by adding its path to `sys.path` in `conf.py` of the docs.
* Update `conf.py`
* Update documentation building command in `CONTRIBUTING.rst`
* Update documentation building test on travis to fail on warnings
This error did not happen locally as we always built the documentation with
```bash
$ python setup.py build_sphinx
```
If you use the command that readthedocs is executing we will get the same error:
```bash
sphinx-build docs/ build/sphinx/html/ -b html
```
which is now fixed.
To be aware of testing this command, I …
=> DOC: fix build on RTD without installing package

README.rst, docs/index.rst, docs/install.rst, docs/usage.rst
Adds a link to the online documentation in a more prominent position.
It also removes the second introduction sentence as I don't think it is needed there as we have the usage section.
=> DOC: add link to RTD page to README

audtorch/transforms/functional.py, tests/test_transforms_functional.py
This pull-request fixes `transforms.Normalize` and `transforms.functional.normalize` for the case when `axis=0`.
This `if-branch`: https://github.com/audeering/audtorch/blob/b575ba527af7d839af3f50ea54915dc92d225f23/audtorch/transforms/functional.py#L252 is also triggered by `axis=0`, which results in the matrix being normalized by its global maximum absolute value, and not by the local one in axis 0.
* Change `if axis` to `if axis is not None`
* Add tests for 2D matrices with `axis=0` and `axis=1`
This should also increase the patch version as it implements a bug fix.
=> Fix normalize axis

audtorch/transforms/functional.py, audtorch/transforms/transforms.py, docs/api-transforms-functional.rst, docs/api-transforms.rst, tests/test_transforms.py, tests/test_transforms_functional.py
Tidy up and extend our existing Spectrogram transforms.
* Add `n_fft` parameter to `stft` functional and `Spectrogram` transform to allow the user to optionally use a different window size than FFT size
* Add `Log` transforms that allows for `magnitude_boost` as well
* Add `standardize` functional and `Standardize` transform that take care of mean and std normalizing a signal, either globally or across an axis.
* Schedule `LogSpectrogram` transform for deprecation as it does not add any extra functionality.
Only if needed:
1. Should I remove `LogSpectrogram` now or should we do it in a later version
2. Should I allow the `Standardize` transform to only do mean-normalization or std-normalization based on some user options? e.g. `mean=True`, `std=True`?
=> Spectrogram reform

CHANGELOG.rst, NEWS.rst, docs/changelog.rst, docs/index.rst, docs/version-history.rst
Just updated to the Changelog format of https://keepachangelog.com/en/1.0.0/.
Rename `NEWS.rst` to `CHANGELOG.rst` and change the heading `Version History` in the docs to `Changelog`.
=> DOC: Switch to changelog format

audtorch/transforms/transforms.py
The output shape of `transform.Spectrogram` was described wrongly in the docstring by switching time and frequency axis. This pull request fixes this.
Interestingly, in `transform.LogSpectrogram` it was already correct.
* Update docstring of `transform.Spectrogram`
=> DOC: fix wrong Spectrogram output shape

setup.py
Add links to our documentation and issue tracker to `setup.py`. Those will then appear as nice extra links [our pypi.org page](https://pypi.org/project/audtorch/), compare the [pypi page of Django](https://pypi.org/project/Django/)
Added `project_urls` to `setup.py`
=> Add documentation and tracker URLs to setup.py

tests/test_samplers.py
In #33 one test on travis failed due to shortage of RAM. This fixes it by reducing the amount of RAM needed by around 3GB.
Factor 10 smaller `max_length` and `max_feature` in `test/test_sampler.py`
1. @shuber: does the test still makes sense with the smaller numbers?
=> TST: reduce RAM usage of test_samplers

audtorch/datasets/audio_set.py, audtorch/datasets/base.py, audtorch/datasets/libri_speech.py, audtorch/datasets/mozilla_common_voice.py, audtorch/datasets/utils.py, tests/test_datasets.py
Fix path handling in data sets.
As discussed in #32 we have errors when providing a relative path to our data sets as internally we used only `os.path.expanduser` which handles paths like `~/tmp`, but not `./tmp`.
* Add the function `safe_path` to `audtorch.datasets.utils`.
* Change all occurrences of `os.path.expanduser` in the data sets to `safe_path`
1. The naming of `safe_path` is maybe not optimal.
2. Unit tests are missing
3. There might also be a better way to deal with the underlying issue as in some cases we actual would like to have relative paths (as maybe in the functions for which this PR fails the tests)
=> Add safe_path to ensure absolute paths

CONTRIBUTING.rst
Of course I forgot something by  during the renaming of `NEWS.rst` to `CHANGELOG.rst`.
The `NEWS.rst` file was mentioned in `CONTRIBUTING.rst`.
Adjust the mentioned `NEWS.rst` entries in `CONTRIBUTING.rst` to `CHANGELOG.rst`.
=> Rename NEWS to CHANGELOG in CONTRIBUTING

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/documentation.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/ISSUE_TEMPLATE/questions-help-support.md
The icons in the headings of our issue templates are broken. This pull request just removes the icons and introduces text only headings which should be sufficient.
=> DOC: remove broken logos from issue templates

audtorch/datasets/libri_speech.py
Removes the call to `os.system` for moving files and replaces it by the solution proposed in #32.
=> Remove os.system call for moving files

CONTRIBUTING.rst
Simplify example call to `virtualenv` as `--no-site-packages` is no longer needed and `python3` is sufficient (and we cannot expect that `/usr/bin/python3` exists on all systems).
=> DOC: simplify virtualenv example

LICENSE, audtorch/datasets/__init__.py, audtorch/datasets/speech_commands.py
As title, added google speech commands dataset, with some choice designs for preprocessing as described in the next section.
- Added speech commands dataset
- Dataset partitioning into train / test using `testing_list.txt` from the dataset download
- `validation_list.txt` is still provided for use to use `sampler` in the dataloader if train/valid/test is desired
- Using `include` keyword for defining custom subset of dataset. All other words in the dataset are marked as `unknown` (not sure if this adheres to the original split, but couldn't find more information about this)
- Using `silence` keyword to include samples from `_background_noise_` folder
1. `silence`: currently the DataSet simply points to samples in the `_background_noise_` folder. These samples are 1min long, whereas the …
=> Added Google Speech Commands V2 Dataset

audtorch/datasets/speech_commands.py, docs/api-datasets.rst, docs/index.rst
* Remove TOC from index (start) page
* Add `datasets.SpeechCommands` to docs
=> DOC: include SpeechCommands and clean up of index

setup.cfg
Fixes the content of the wheel package
I thought that using `packages = audtorch` is sufficient, but this only works if you don't have sub-folders (or if you use `include_package_data = True`).
I changed it now to `packages = find:` and it works:
```bash
$ python setup.py sdist bdist_wheel
...
creating build/bdist.linux-x86_64/wheel/audtorch-0.4.2.dev1+g93bbc93.d20191104.dist-info/WHEEL
creating 'dist/audtorch-0.4.2.dev1+g93bbc93.d20191104-py3-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
adding 'audtorch/__init__.py'
adding 'audtorch/collate.py'                    
adding 'audtorch/samplers.py'                 
adding 'audtorch/utils.py'
adding 'audtorch/datasets/__init__.py'                  
adding 'audtorch/datasets/audio_set.py'
adding 'audtorch/datasets/base.py' …
```
=> Include all modules in wheel

audtorch/transforms/functional.py, audtorch/transforms/transforms.py
We added `librosa` now as a dependency in `setup.cfg`, which means we can switch to a normal import of it in the transforms.
Replace `try`-`except` with simple `import`.
=> Switch to normal import for librosa

audtorch/transforms/functional.py
There seems to be a change in `numpy` or whereever that `+0j` is now returned as `-0j`.
=> Fix stft functional example

audtorch/datasets/audio_set.py, audtorch/datasets/base.py, audtorch/datasets/mozilla_common_voice.py, audtorch/datasets/speech_commands.py, audtorch/datasets/utils.py, audtorch/datasets/voxceleb1.py, tests/test_datasets.py
Improvement of base data classes.
1. Make `root` argument optional as it is totally valid to use absolute paths in file lists. This also makes the overall interface slightly easier to implement.
2. Add `duration` and `offset` attribute to `AudioDataset`, which means all others will have it as well.
3. Add `column_start` and `column_end` to `PandasDataset` and `CsvDataset`, which will be translated into the `duration` and `offset` attributes.
4. Allow for `column_labels=None`, which will return `''` as target
5. All basic data sets in `base.py` are now keyword only to not break the API later on.
What I have not changed, but we discussed it before is:
1. The default value of `column_filename` is still `filename`.
=> Enhance basic data sets

.github/workflows/publish.yml, CONTRIBUTING.rst
Uses a Github Action to:
* build and upload docs as Github pages
* build and upload Python package to PyPI server
* create a release on Github including the latest changelog automatically
=> Automate publication of doc and Python package

.github/workflows/publish.yml
The last publishing failed when trying to install `torch`: https://github.com/audeering/audtorch/runs/1330863465?check_suite_focus=true
But this is also not needed for just building the documentation.
=> Only install doc requirements when publishing

setup.cfg
Fix link in Python package to point to documentation on Github pages
=> Update documentation link in Python package

docs/conf.py, docs/requirements.txt
The new version of `sphinxcontrib-bibtex` requires another config entry, otherwise it will break the compilation of the docs.
=> DOC: use sphinxcontrib-bibtex>=2.1.0
